spring.application.name=NewNetworkingBackend

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.password=12345678
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE AUTO-GENERATION CONFIGURATION ---
# 'update' will create the table if it doesn't exist, or modify it if you change your Java entity.
spring.jpa.hibernate.ddl-auto=update

# This shows the actual SQL Hibernate executes in your console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true